stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - docker pull wordpress:latest
    - docker build -t qiushaocloud/wordpress-ssl-docker:latest .
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - docker push qiushaocloud/wordpress-ssl-docker:latest
  tags:
    - qiushaocloud-runner
