version: "3.3"
 
services:
  qiushaocloud-wordpress-db-server:
    image: mysql:5.7
    container_name: qiushaocloud-wordpress-db-server
    hostname: qiushaocloud-wordpress-db-server
    restart: "always"
    volumes:
      - $WORDPRESS_DB_DATA_PATH:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      MYSQL_USER: $WORDPRESS_DB_USER
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD

  qiushaocloud-wordpress-server:
    depends_on:
      - qiushaocloud-wordpress-db-server
    image: qiushaocloud/wordpress-ssl-docker:latest
    container_name: qiushaocloud-wordpress-server
    hostname: qiushaocloud-wordpress-server
    restart: always
    ports:
      - "$EXPORT_SERVER_PORT:#WP_CONTAINER_PORT"
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DEBUG: $WORDPRESS_DEBUG
      SSL_KEY_PATH: $SSL_KEY_PATH
      SSL_CRT_PATH: $SSL_CRT_PATH
      WP_CONTAINER_PORT: $WP_CONTAINER_PORT
    volumes:
      - $WORDPRESS_DATA_PATH:/var/www/html
      - ./ssl:/ssl