version: "3.3"
 
services:
  qiushaocloud-wordpress-server:
    image: qiushaocloud/wordpress-ssl-docker:latest
    container_name: qiushaocloud-wordpress-server
    hostname: qiushaocloud-wordpress-server
    restart: always
    ports:
      - "$EXPORT_HTTP_PORT:80"
      - "$EXPORT_HTTPS_PORT:443"
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DEBUG: $WORDPRESS_DEBUG
      SSL_KEY_PATH: $SSL_KEY_PATH
      SSL_CRT_PATH: $SSL_CRT_PATH
      FORCE_HTTPS: $FORCE_HTTPS
    volumes:
      - $WORDPRESS_DATA_PATH:/var/www/html
      - ./ssl_cetrts:/ssl_cetrts